DROP TABLE STAFF;
CREATE TABLE STAFF
(
    SNO VARCHAR2(5 BYTE) NOT NULL PRIMARY KEY,
    NAME VARCHAR2(32 BYTE),
    DEPT VARCHAR2(20 BYTE) NOT NULL,
    SALARY NUMBER NOT NULL
);

DROP SEQUENCE STAFF_SEQ;
CREATE SEQUENCE STAFF_SEQ NOCACHE;

INSERT INTO STAFF(SNO, NAME, DEPT, SALARY)
VALUES(STAFF_SEQ.NEXTVAL, 1111, '설경구', '기획부', 5000);
VALUES(STAFF_SEQ.NEXTVAL, 2222, '전지현', '개발부', 6000);
VALUES(STAFF_SEQ.NEXTVAL, 3333, '정우성', '영업부', 7000);
COMMIT;